name: Terraform Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.11.3
      - name: Terraform Format
        run: terraform fmt -check
        working-directory: Task1

  terraform-plan:
    runs-on: ubuntu-latest
    needs: [terraform-check]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.11.3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::650251696415:role/GithubActionsRole
          aws-region: us-east-1
      - name: Terraform Init
        run: terraform init -reconfigure
        working-directory: Task1
      - name: Terraform Plan
        run: terraform plan
        working-directory: Task1

  terraform-apply:
    runs-on: ubuntu-latest
    needs: [terraform-plan]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.11.3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::650251696415:role/GithubActionsRole
          aws-region: us-east-1
      - name: Terraform Init
        run: terraform init -reconfigure
        working-directory: Task1
      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: Task1
